### ISSUE TITLE
Burst Bombs

### ISSUE THREAD

**Issue by LAGRIENZO** [selicia/splat2-calc#1]
I'm pretty sure the stat calculations for Burst Bomb aren't updated from the nerf. The calculator claims that three bombs can be thrown with less than 3.2 ISS or 2.6 ISS, which is simply false.

**Comment by selicia** [comment]
Thank you for pointing this out! I believe I found the cause. In stats.js the calculations for ISS were referencing `loadout.weapon.inkSaver` instead of `loadout.weapon.sub.inkSaver`. Should be an easy fix!

**Comment by Leanny** [comment]
The bug is actually that the implementation of the new ISS System is not done yet. Burst bomb is just the only one with a new type that is not yet implemented

**Comment by selicia** [comment]
Commit 293e8d0578743d78da833f031a48b6fd8c4403cd fixed this issue.
