### ISSUE TITLE
Run Speed (Firing) for Splatlings

### ISSUE THREAD

**Issue by nikuD29** [selicia/splat2-calc#11]
RSU while shooting scales differently for Splatlings of different move types.
Source: https://twitter.com/LeanYoshi/status/1070145577709694977

**Comment by selicia** [comment]
I'm seeing the varying Run Speed (Firing) values for each Splatling. Just to confirm, are you using the current beta link for Loadout? https://selicia.github.io/en_US/

![BallpointSpatlingRunSpeedFiring](https://user-images.githubusercontent.com/28240251/56039110-8d63f700-5d01-11e9-8d7a-058c8ca074e9.PNG)
![KensaMiniSplatingRunSpeedFiring](https://user-images.githubusercontent.com/28240251/56039128-95239b80-5d01-11e9-81a9-fe6541e6f5a1.PNG)

**Comment by selicia** [comment]
Thank you for reporting this bug!

0ee5715236c860296a672b8a8629cd26e42f0ae6 Should fix this. It will be in the build deployed tonight. I'll leave this issue open so you can confirm the values are what you expect.

**Comment by IAmDoctorNo** [comment]
Actually, on that note, could you show the effects of RSU on Splatlings while firing _and_ charging?

**Comment by selicia** [comment]
Do you mean in addition to the two bars already displayed? There's both Run Speed and Run Speed (Firing), both of which use the parameters for the weapon you've selected.

**Comment by selicia** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add a way to toggle the Run Speed (Firing) bar for Splatlings to switch to Run Speed (Charging).](https://trello.com/c/sJYZW1sq/36-add-a-way-to-toggle-the-run-speed-firing-bar-for-splatlings-to-switch-to-run-speed-charging)

**Comment by nikuD29** [comment]
According to http://leanny.github.io/splat2/en_files.html and http://leanny.github.io/paper/abilities_appendix.pdf, Run Speed (Firing) for Ballpoint Splatling of shooting type B should cap at +25% with max (57 AP) RSU.
Nautilus caps at +30%.
Heavy Splatling and Hydra Splatling cap at +35%.
Mini Splatling caps at +40%.

**Comment by selicia** [comment]
Following up with Lean to update to the 4.3+ run speed data.

**Comment by selicia** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update Run Speed Calculations](https://trello.com/c/jAsnvZGF/37-update-run-speed-calculations)

**Comment by selicia** [comment]
c17a66dfdbaa34eeb4d32e966c07aa6e156d4744 Updated all weapon speeds to current v4.6 values. Added new Run Speed (Firing) weapon Types (A,B,C,etc) for each weapon. Updated Run Speed (Firing) calculations to use new values.

Also added a **New Feature**: Clicking on the title of a stat, such as _Run Speed (Firing)_ will change the stat to a secondary value if applicable. For Splatlings and Brellas doing so will change the stat bar to display _Run Speed (Charging)_.
