### ISSUE TITLE
The Effect of Bomb Defense Up DX

### ISSUE THREAD

**Issue by nikuD29** [selicia/splat2-calc#16]
The effect of Bomb Defense Up DX on reducing tracking time was updated in patch 4.5.0
https://twitter.com/LeanYoshi/status/1105154639459176448

**Comment by selicia** [comment]
Thanks for the bug report. You're right, Point Sensor's curve changed. The "mid" param I'm using needs to be updated to be 0.43.

**Comment by selicia** [comment]
e59cb1c4070a80bd4c3d3bb6b3cf918267b1e46d Fixes this and adds a toggle for the Tracking Time stat to switch between Point Sensor & Ink Mine.

**Comment by nikuD29** [comment]
The base duration of Ink Mine is 5s instead of 8s.

**Comment by selicia** [comment]
Thanks for catching that too. I'll fix it in the next update.

**Comment by selicia** [comment]
e2d9576f0035781b2c3bf35bdbf98133b8e8a4bc Corrects the base duration of Ink Mine to 5s.
