### ISSUE TITLE
Invulnerability Time of Ink Resistance Up

### ISSUE THREAD

**Issue by nikuD29** [selicia/splat2-calc#18]
Maybe I understand it wrong, is Invulnerability Time the same thing as Armor Duration in https://twitter.com/LeanYoshi/status/1091417447024988161 ? I think it is since with max IRU, 39 frames / 60 frames = 0.65s. But the curve doesn't match.

**Comment by selicia** [comment]
Yes, you're correct - Armor Duration is the Invulnerability Time.
251f934d08332ac9bfc031afb84f8fb51b6b3005 Fixes the Armor Duration values for Ink Res, and thus the curve. However, I haven't pushed these changes to the live beta yet.

**Comment by selicia** [comment]
The live beta now has this change.
