### ISSUE TITLE
Splattershot MPU Wrong Value

### ISSUE THREAD

**Issue by nikuD29** [selicia/splat2-calc#19]
The MPU values for Splattershot are incorrect. The curve should be the same as .52 Gal.

**Comment by selicia** [comment]
Working on a large update that will be updating all weapon damage values and MPU parameters.

**Comment by selicia** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update ALL Weapon Damage and MPU Param Updates (using 4.7 data)](https://trello.com/c/TbhV4tA6/53-update-all-weapon-damage-and-mpu-param-updates-using-47-data)

**Comment by selicia** [comment]
07415a4927ce0a5f0df168eafccbde56af7fe6f8 Fixes this. However, it won't be pushed to the live beta until the MPU calculations are updated.

**Comment by selicia** [comment]
The live beta now has all of the MPU changes. Please confirm you see the fix and close the issue if it works, or let me know if you're still seeing incorrect values.
