### ISSUE TITLE
Rapid Blaster/Rapid Blaster Pro MPU(Damage Radius)

### ISSUE THREAD

**Issue by nikuD29** [selicia/splat2-calc#21]
The effect caps at 29AP instead of 57AP.

**Comment by selicia** [comment]
Thanks for the heads-up. I'll include a fix for this in the next release.

**Comment by selicia** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Rapid Blaster & Rapid Blast Pro MPU Caps](https://trello.com/c/REmFUYi4/63-rapid-blaster-rapid-blast-pro-mpu-caps)

**Comment by selicia** [comment]
Looked into this some more. I wasn't aware there was a cap on the damage radius other than the max AP modifier. You're right that ~29 AP is approximately hitting the cap. I'll update the code so it uses the base Damage Radius values and strictly applies the modifier calculated from the AP with a check for the cap. Will take a little bit more work than I originally thought. Are you aware of any other weapons that have MPU stat caps?

Example data taken from Lean's data below:
```
CollisionRadiusMiddle: 33
CollisionRadiusMiddle_MWPUG_Max: 35
CollisionRadiusMiddleRate_MWPUG_High: 1.093939
CollisionRadiusMiddleRate_MWPUG_Mid: 1.036364
```

**Comment by nikuD29** [comment]
As far as I know, this is the only non-Damage-Up MPU that has a cap. I also found L3 MPU not displaying when I was checking it through.

**Comment by selicia** [comment]
4adfa20a72015c9f82839d81660d3b564ad3f43a Fixes the Rapid Blaster & Rapid Blaster Pro MPU caps.
58cd4da19bcd7ccf9e4bc419e27f750ad308f0c9 Fixes the L-3 Nozzelnose bug that was preventing MPU from displaying.

**Comment by selicia** [comment]
Fixes are live!
