### ISSUE TITLE
Main Power Up errors

### ISSUE THREAD

**Issue by IAmDoctorNo** [selicia/splat2-calc#6]
The following main weapons have incorrect MPU scaling:
Splattershot Pro (Reaches 49.9 at 3m3s MPU now, not 1m7s)
Bamboozler Mk. I (Reaches 99.9 at 2m7s MPU, not 3m9s)

The following main weapons that have increased damage from MPU do not cap their max damage at the appropriate thresholds when using too much MPU:
Dualie Squelchers (Should cap at 33.33)
Dark Tetra Dualies (Should cap at 33.33)
H-3 Nozzlenose (Should cap at 49.99)
Splat Dualies (Should cap at 33.33)
Splattershot Pro (Should cap at 49.99)
L-3 Nozzlenose (Should cap at 33.33)

**Comment by selicia** [comment]
Hey, thanks for reporting this! I'll update the MPU values for Splattershot Pro and Bamboozler once I get the v4.6 MPU parameters. As for the other weapon's capped values, I'll update those now.

**Comment by selicia** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix MPU caps for various weapons.](https://trello.com/c/areajRHR/26-fix-mpu-caps-for-various-weapons)

**Comment by selicia** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix MPU parameters for weapons changed in v4.6](https://trello.com/c/MNzwHBfx/27-fix-mpu-parameters-for-weapons-changed-in-v46)

**Comment by selicia** [comment]
ea28e7cab99fea1ac02679a1647141ec7ffa94cc Added MPU damage caps for the weapons listed. Splattershot Pro and Bamboozler need their MPU parameters updated.

**Comment by selicia** [comment]
The MPU parameters for Splattershot Pro & Bamboozler were incorrect. Lean provided me with the right values to use. Commit 929f9fc100a020df5ed947464b884f1c3c5bd771 uses the new values and caps the Bamboozler at 99.9.
