### ISSUE TITLE
Subs

### ISSUE THREAD

**Issue by OscarC123** [selicia/splat2-calc#8]
Ink consumption on autobombs and point sensors were updated in later patches. Point sensors dropped to 45% and autobombs dropped to 55%

**Comment by selicia** [comment]
Thank you for reporting this! I'll take a look and try to get a fix included in tonight's update.

**Comment by selicia** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update Sub-weapon Ink Consumption (cost) Values](https://trello.com/c/6ydxTzby/34-update-sub-weapon-ink-consumption-cost-values)

**Comment by selicia** [comment]
10dadc7dcc78ba55730e98b4e405bc9ae3c61a92 Fixes this.
